### ISSUE TITLE
tracker issue for non-Expr in matrices

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1124]
We have various issues stemming from upstream SymPy's decision (sensible decision, that is!) to not allow things that are not expressions into matrices.

Examples of things we do:
- True/False
- Equations/Inequalities:  `Eq(x, y)` in Python
- `None`

I'll link issues / failing tests / etc to this Issue number.

## TODO list

- [ ] failing test in `isNone`
- more

**Comment by cbm755** [comment]
For 3.0.0, we don't need permanent fix (its only deprecated upstream), but of course would be nice...

**Comment by alexvong1995** [comment]
I think the the test failure is partly due to `dbout` being define in `inst/private/python_header.py` (for non-Pythonic IPC) but not in `inst/private/python_ipc_native.m` (for Pythonic IPC).

I'm not sure what to do about it. It seems there're more code in `inst/private/python_header.py` than in `inst/private/python_ipc_native.m`.

**Comment by cbm755** [comment]
> Alternatively if the goal is just printing support then perhaps TableForm can be used.

https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-non-expr-in-matrix

@alexvong1995  We should investigate whether TableForm would work instead of Array.

**Comment by alexvong1995** [comment]
From the doc-string of `TableForm`, the only documented way to extract the original data is to use `as_matrix()`, which is obviously not what we want. One can do it using the undocumented attribute of `_lines` though.

```
Help on class TableForm in module sympy.printing.tableform:

class TableForm(builtins.object)
 |  TableForm(data, **kwarg)
 |  
 |  Create a nice table representation of data.
 |  
 |  Examples
 |  ========
 |  
 |  >>> from sympy import TableForm
 |  >>> t = TableForm([[5, 7], [4, 2], [10, 3]])
 |  >>> print(t)
 |  5  7
 |  4  2
 |  10 3
 |  
 |  You can use the SymPy's printing system to produce tables in any
 |  format (ascii, latex, html, ...).
 |  
 |  >>> print(t.as_latex())
 |  \begin{tabular}{l l}
 |  $5$ & $7$ \\
 |  $4$ & $2$ \\
 |  $10$ & $3$ \\
 |  \end{tabular}
 |  
 |  Methods defined here:
 |  
 |  __init__(self, data, **kwarg)
 |      Creates a TableForm.
 |      
 |      Parameters:
 |      
 |          data ...
 |                          2D data to be put into the table; data can be
 |                          given as a Matrix
 |      
 |          headings ...
 |                          gives the labels for rows and columns:
 |      
 |                          Can be a single argument that applies to both
 |                          dimensions:
 |      
 |                              - None ... no labels
 |                              - "automatic" ... labels are 1, 2, 3, ...
 |      
 |                          Can be a list of labels for rows and columns:
 |                          The labels for each dimension can be given
 |                          as None, "automatic", or [l1, l2, ...] e.g.
 |                          ["automatic", None] will number the rows
 |      
 |                          [default: None]
 |      
 |          alignments ...
 |                          alignment of the columns with:
 |      
 |                              - "left" or "<"
 |                              - "center" or "^"
 |                              - "right" or ">"
 |      
 |                          When given as a single value, the value is used for
 |                          all columns. The row headings (if given) will be
 |                          right justified unless an explicit alignment is
 |                          given for it and all other columns.
 |      
 |                          [default: "left"]
 |      
 |          formats ...
 |                          a list of format strings or functions that accept
 |                          3 arguments (entry, row number, col number) and
 |                          return a string for the table entry. (If a function
 |                          returns None then the _print method will be used.)
 |      
 |          wipe_zeros ...
 |                          Do not show zeros in the table.
 |      
 |                          [default: True]
 |      
 |          pad ...
 |                          the string to use to indicate a missing value (e.g.
 |                          elements that are None or those that are missing
 |                          from the end of a row (i.e. any row that is shorter
 |                          than the rest is assumed to have missing values).
 |                          When None, nothing will be shown for values that
 |                          are missing from the end of a row; values that are
 |                          None, however, will be shown.
 |      
 |                          [default: None]
 |      
 |      Examples
 |      ========
 |      
 |      >>> from sympy import TableForm, Symbol
 |      >>> TableForm([[5, 7], [4, 2], [10, 3]])
 |      5  7
 |      4  2
 |      10 3
 |      >>> TableForm([list('.'*i) for i in range(1, 4)], headings='automatic')
 |        | 1 2 3
 |      ---------
 |      1 | .
 |      2 | . .
 |      3 | . . .
 |      >>> TableForm([[Symbol('.'*(j if not i%2 else 1)) for i in range(3)]
 |      ...            for j in range(4)], alignments='rcl')
 |          .
 |        . . .
 |       .. . ..
 |      ... . ...
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  __str__(self)
 |      Return str(self).
 |  
 |  as_latex(self)
 |  
 |  as_matrix(self)
 |      Returns the data of the table in Matrix form.
 |      
 |      Examples
 |      ========
 |      
 |      >>> from sympy import TableForm
 |      >>> t = TableForm([[5, 7], [4, 2], [10, 3]], headings='automatic')
 |      >>> t
 |        | 1  2
 |      --------
 |      1 | 5  7
 |      2 | 4  2
 |      3 | 10 3
 |      >>> t.as_matrix()
 |      Matrix([
 |      [ 5, 7],
 |      [ 4, 2],
 |      [10, 3]])
 |  
 |  as_str(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
```

**Comment by alexvong1995** [comment]
Is putting non-`Expr` in `Array` officially supported? If not, using an undocumented attribute could be a less bad option going forward...

**Comment by alexvong1995** [comment]
In any case, I think our approach should be general enough such that this implementation details doesn't matter. There should be minimal code change regardless of which concrete type we decide to use. It's possible that sympy will introduce a new type in the future that we will want to switch to.

Concretely, I think we should change `make_matrix_or_array` to be something more general. I would suggest changing its name to `make_2d_sym`. WDYT? It should take an iterable of iterables as inputs instead of only supporting a list of lists.

Also, we may want to create some more help functions such as `is_2d_sym`, `is_non_matrix_2d_sym` to abstract over the implementation details. WDYT?

**Comment by cbm755** [comment]
Those ideas sound good to me.  New names sound fine.

Uncertain about lack of indexing in tableForm but as you say should be easy to refactor later.

**Comment by cbm755** [comment]
re: TableForm versus Array.  I'm less certain about the lack indexing: I've just filed #1223 and #1224 which are examples of using linear indexing into Matrix needing adjustment b/c linear indexing does not work with Array (filed https://github.com/sympy/sympy/issues/24007).  That problem would get even worse if we need to abstract **all** indexing for TableForm.

**Comment by cbm755** [comment]
### list of methods that have failing tests

- [x] stuff from uniop_helper and elementwise op #1223, #1224
    - forget exactly what this fixed...
- [x] subs #1226 #1227 
    - [x] and/or/xor fixed by #1227
- [ ] subsasgn
- [ ] dsolve
- [ ] solve
- [ ] find
- [ ] in/un/equalities
    - [ ] eq
    - [ ] ne
    - [ ] lt, gt
    - [ ] le, ge
- likely related:
    - [ ] logical
    - [ ] isNone
    - [ ] isAlways
- equationsToMatrix

**Comment by cbm755** [comment]
Yeah its strange, I got a bunch of notifications last night.  Some maybe even older (like months ago).

**Comment by cbm755** [comment]
And not just from you @alexvong1995.   @chrisjohgorman: for some reason we are getting delayed replies; no action required I guess (?)
